site_name: 个人博客
copyright: Copyright &copy; 2023 - 2023 Lei
repo_url:  https://github.com/908760230/MyBlog
repo_name: Github
nav:
    - 索引: index.md
    - c++: 
        - 目录: c++/0目录.md 
    - 数据结构:
        - 数据结构是什么: DataStruct/1-数据结构是什么.md
        - 算法: DataStruct/2-算法.md
        - 线性表-顺序表: DataStruct/3-线性表-顺序表.md
        - 线性表-链表: DataStruct/4-线性表-链表.md
        - 循环链表: DataStruct/5-循环链表.md
        - 双向链表: DataStruct/6-双向链表.md
        - 静态链表: DataStruct/7-静态链表.md
        - 栈: DataStruct/8-栈.md
        - 队列: DataStruct/9-队列.md
        - 串: DataStruct/10-串.md
        - 数组: DataStruct/11-数组.md
        - 稀疏矩阵的压缩-三元组表（转置）: /12-稀疏矩阵的压缩-三元组表-转置.md
        - 稀疏矩阵的压缩-三元组（相乘）: /13-稀疏矩阵的压缩-三元组-相乘.md
        - 稀疏矩阵的压缩-十字链表: DataStruct/14-稀疏矩阵的压缩-十字链表.md
        - 树: DataStruct/15-树.md
        
theme:
    icon:
        repo: fontawesome/brands/github
    language: zh
    name: material
    custom_dir: docs/Stylesheet
    features:
        - content.code.annotate
        - content.code.copy
        - content.tooltips
        - navigation.expand
        - navigation.footer
        - navigation.indexes
        - navigation.sections
        - navigation.instant
        - navigation.tabs
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
        - announce.dismiss
    palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
markdown_extensions:
    - abbr
    - admonition
    - def_list
    - footnotes
    - md_in_html
    - toc:
        permalink: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink:
        repo_url_shorthand: true
        user: squidfunk
        repo: mkdocs-material
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
extra_css:
  - Stylesheet/mkdocs_extra.css
plugins:
    - glightbox
    - search:
        separator: '[\s\u200b\-]'
    - git-revision-date-localized:
        enable_creation_date: true
        type: iso_datetime
    - git-committers:
        repository: 908760230/MyBlog
        branch: main
        docs_path: docs
        enabled: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/908760230
    - icon: fontawesome/brands/qq
      title: 1508859213
    - icon: simple/zhihu
      link: https://www.zhihu.com
  copyright: Copyright &copy; 2016 - 2020 Martin Donath