# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: pip install mkdocs-material 
      
      - name: Install Python dependencies
        run: |
          pip install \
            "cairosvg>=2.5" \
            "jieba" \
            "mkdocs-git-committers-plugin-2>=1.1.1" \
            "mkdocs-git-revision-date-localized-plugin>=1.0" \
            "mkdocs-minify-plugin>=0.3" \
            "mkdocs-rss-plugin>=1.2" \
            "mkdocs-redirects>=1.0" \
            "mkdocs-glightbox" \
            "pillow<10"
      
      - name: setup busuanzi
        run: |
          MKDOCS_MATERIAL_PATH=$(pip show mkdocs-material | grep 'Location:' | awk '{print $2}')
          sed -i 's/<\/article>/<hr><span id="busuanzi_container_page_pv"><font size="3" color="grey">本文总阅读量<span id="busuanzi_value_page_pv"><\/span>次  <\/font><\/span><span id="busuanzi_container_site_uv"><font size="3" color="grey">本站访客数<span id="busuanzi_value_site_uv"><\/span>人次<\/font><\/span><br\/><\/article>/g' "$MKDOCS_MATERIAL_PATH/material/templates/base.html"

      - name: Deploy documentation
        run: |
          mkdocs gh-deploy --force
          mkdocs --version